import type { Award } from './types'

/** One winner as the award announced it: the year it was presented, the title
 *  it won under — the English one, every award below being given to books in
 *  English — and its authors. */
export type WinnerEntry = readonly [year: number, title: string, authors: string]

/** The winners of each award, novel category only, finalists never. The year is
 *  the year of the ceremony, not of publication: SFWA labels a Nebula by the
 *  year the book came out, so its rows are shifted by one to match the others.
 *  Co-authors are separated by " & ". Ties are two rows under one year.
 *
 *  Historical facts, versioned rather than looked up: one commit after each
 *  ceremony. Checked against the awards' own lists, the Science Fiction Awards
 *  Database and Wikipedia on 2026-10-08; `scripts/check-award-winners.ts`
 *  compares them to Wikidata. */
export const WINNERS: Record<Award, readonly WinnerEntry[]> = {
  hugo: [
    [1953, 'The Demolished Man', 'Alfred Bester'],
    [1955, "They'd Rather Be Right", 'Mark Clifton & Frank Riley'],
    [1956, 'Double Star', 'Robert A. Heinlein'],
    [1958, 'The Big Time', 'Fritz Leiber'],
    [1959, 'A Case of Conscience', 'James Blish'],
    [1960, 'Starship Troopers', 'Robert A. Heinlein'],
    [1961, 'A Canticle for Leibowitz', 'Walter M. Miller Jr.'],
    [1962, 'Stranger in a Strange Land', 'Robert A. Heinlein'],
    [1963, 'The Man in the High Castle', 'Philip K. Dick'],
    [1964, 'Way Station', 'Clifford D. Simak'],
    [1965, 'The Wanderer', 'Fritz Leiber'],
    [1966, 'Dune', 'Frank Herbert'],
    [1966, 'This Immortal', 'Roger Zelazny'],
    [1967, 'The Moon Is a Harsh Mistress', 'Robert A. Heinlein'],
    [1968, 'Lord of Light', 'Roger Zelazny'],
    [1969, 'Stand on Zanzibar', 'John Brunner'],
    [1970, 'The Left Hand of Darkness', 'Ursula K. Le Guin'],
    [1971, 'Ringworld', 'Larry Niven'],
    [1972, 'To Your Scattered Bodies Go', 'Philip José Farmer'],
    [1973, 'The Gods Themselves', 'Isaac Asimov'],
    [1974, 'Rendezvous with Rama', 'Arthur C. Clarke'],
    [1975, 'The Dispossessed', 'Ursula K. Le Guin'],
    [1976, 'The Forever War', 'Joe Haldeman'],
    [1977, 'Where Late the Sweet Birds Sang', 'Kate Wilhelm'],
    [1978, 'Gateway', 'Frederik Pohl'],
    [1979, 'Dreamsnake', 'Vonda N. McIntyre'],
    [1980, 'The Fountains of Paradise', 'Arthur C. Clarke'],
    [1981, 'The Snow Queen', 'Joan D. Vinge'],
    [1982, 'Downbelow Station', 'C. J. Cherryh'],
    [1983, "Foundation's Edge", 'Isaac Asimov'],
    [1984, 'Startide Rising', 'David Brin'],
    [1985, 'Neuromancer', 'William Gibson'],
    [1986, "Ender's Game", 'Orson Scott Card'],
    [1987, 'Speaker for the Dead', 'Orson Scott Card'],
    [1988, 'The Uplift War', 'David Brin'],
    [1989, 'Cyteen', 'C. J. Cherryh'],
    [1990, 'Hyperion', 'Dan Simmons'],
    [1991, 'The Vor Game', 'Lois McMaster Bujold'],
    [1992, 'Barrayar', 'Lois McMaster Bujold'],
    [1993, 'A Fire Upon the Deep', 'Vernor Vinge'],
    [1993, 'Doomsday Book', 'Connie Willis'],
    [1994, 'Green Mars', 'Kim Stanley Robinson'],
    [1995, 'Mirror Dance', 'Lois McMaster Bujold'],
    [1996, 'The Diamond Age', 'Neal Stephenson'],
    [1997, 'Blue Mars', 'Kim Stanley Robinson'],
    [1998, 'Forever Peace', 'Joe Haldeman'],
    [1999, 'To Say Nothing of the Dog', 'Connie Willis'],
    [2000, 'A Deepness in the Sky', 'Vernor Vinge'],
    [2001, 'Harry Potter and the Goblet of Fire', 'J. K. Rowling'],
    [2002, 'American Gods', 'Neil Gaiman'],
    [2003, 'Hominids', 'Robert J. Sawyer'],
    [2004, 'Paladin of Souls', 'Lois McMaster Bujold'],
    [2005, 'Jonathan Strange & Mr Norrell', 'Susanna Clarke'],
    [2006, 'Spin', 'Robert Charles Wilson'],
    [2007, 'Rainbows End', 'Vernor Vinge'],
    [2008, "The Yiddish Policemen's Union", 'Michael Chabon'],
    [2009, 'The Graveyard Book', 'Neil Gaiman'],
    [2010, 'The City & the City', 'China Miéville'],
    [2010, 'The Windup Girl', 'Paolo Bacigalupi'],
    [2011, 'Blackout/All Clear', 'Connie Willis'],
    [2012, 'Among Others', 'Jo Walton'],
    [2013, 'Redshirts', 'John Scalzi'],
    [2014, 'Ancillary Justice', 'Ann Leckie'],
    [2015, 'The Three-Body Problem', 'Cixin Liu'],
    [2016, 'The Fifth Season', 'N. K. Jemisin'],
    [2017, 'The Obelisk Gate', 'N. K. Jemisin'],
    [2018, 'The Stone Sky', 'N. K. Jemisin'],
    [2019, 'The Calculating Stars', 'Mary Robinette Kowal'],
    [2020, 'A Memory Called Empire', 'Arkady Martine'],
    [2021, 'Network Effect', 'Martha Wells'],
    [2022, 'A Desolation Called Peace', 'Arkady Martine'],
    [2023, 'Nettle & Bone', 'T. Kingfisher'],
    [2024, 'Some Desperate Glory', 'Emily Tesh'],
    [2025, 'The Tainted Cup', 'Robert Jackson Bennett'],
    [2026, 'The Everlasting', 'Alix E. Harrow'],
  ],
  nebula: [
    [1966, 'Dune', 'Frank Herbert'],
    [1967, 'Flowers for Algernon', 'Daniel Keyes'],
    [1967, 'Babel-17', 'Samuel R. Delany'],
    [1968, 'The Einstein Intersection', 'Samuel R. Delany'],
    [1969, 'Rite of Passage', 'Alexei Panshin'],
    [1970, 'The Left Hand of Darkness', 'Ursula K. Le Guin'],
    [1971, 'Ringworld', 'Larry Niven'],
    [1972, 'A Time of Changes', 'Robert Silverberg'],
    [1973, 'The Gods Themselves', 'Isaac Asimov'],
    [1974, 'Rendezvous with Rama', 'Arthur C. Clarke'],
    [1975, 'The Dispossessed', 'Ursula K. Le Guin'],
    [1976, 'The Forever War', 'Joe Haldeman'],
    [1977, 'Man Plus', 'Frederik Pohl'],
    [1978, 'Gateway', 'Frederik Pohl'],
    [1979, 'Dreamsnake', 'Vonda N. McIntyre'],
    [1980, 'The Fountains of Paradise', 'Arthur C. Clarke'],
    [1981, 'Timescape', 'Gregory Benford'],
    [1982, 'The Claw of the Conciliator', 'Gene Wolfe'],
    [1983, 'No Enemy But Time', 'Michael Bishop'],
    [1984, 'Startide Rising', 'David Brin'],
    [1985, 'Neuromancer', 'William Gibson'],
    [1986, "Ender's Game", 'Orson Scott Card'],
    [1987, 'Speaker for the Dead', 'Orson Scott Card'],
    [1988, 'The Falling Woman', 'Pat Murphy'],
    [1989, 'Falling Free', 'Lois McMaster Bujold'],
    [1990, "The Healer's War", 'Elizabeth Ann Scarborough'],
    [1991, 'Tehanu', 'Ursula K. Le Guin'],
    [1992, 'Stations of the Tide', 'Michael Swanwick'],
    [1993, 'Doomsday Book', 'Connie Willis'],
    [1994, 'Red Mars', 'Kim Stanley Robinson'],
    [1995, 'Moving Mars', 'Greg Bear'],
    [1996, 'The Terminal Experiment', 'Robert J. Sawyer'],
    [1997, 'Slow River', 'Nicola Griffith'],
    [1998, 'The Moon and the Sun', 'Vonda N. McIntyre'],
    [1999, 'Forever Peace', 'Joe Haldeman'],
    [2000, 'Parable of the Talents', 'Octavia E. Butler'],
    [2001, "Darwin's Radio", 'Greg Bear'],
    [2002, 'The Quantum Rose', 'Catherine Asaro'],
    [2003, 'American Gods', 'Neil Gaiman'],
    [2004, 'The Speed of Dark', 'Elizabeth Moon'],
    [2005, 'Paladin of Souls', 'Lois McMaster Bujold'],
    [2006, 'Camouflage', 'Joe Haldeman'],
    [2007, 'Seeker', 'Jack McDevitt'],
    [2008, "The Yiddish Policemen's Union", 'Michael Chabon'],
    [2009, 'Powers', 'Ursula K. Le Guin'],
    [2010, 'The Windup Girl', 'Paolo Bacigalupi'],
    [2011, 'Blackout/All Clear', 'Connie Willis'],
    [2012, 'Among Others', 'Jo Walton'],
    [2013, '2312', 'Kim Stanley Robinson'],
    [2014, 'Ancillary Justice', 'Ann Leckie'],
    [2015, 'Annihilation', 'Jeff VanderMeer'],
    [2016, 'Uprooted', 'Naomi Novik'],
    [2017, 'All the Birds in the Sky', 'Charlie Jane Anders'],
    [2018, 'The Stone Sky', 'N. K. Jemisin'],
    [2019, 'The Calculating Stars', 'Mary Robinette Kowal'],
    [2020, 'A Song for a New Day', 'Sarah Pinsker'],
    [2021, 'Network Effect', 'Martha Wells'],
    [2022, 'A Master of Djinn', 'P. Djèlí Clark'],
    [2023, 'Babel', 'R. F. Kuang'],
    [2024, 'The Saint of Bright Doors', 'Vajra Chandrasekera'],
    [2025, 'Someone You Can Build a Nest In', 'John Wiswell'],
    [2026, 'The Buffalo Hunter Hunter', 'Stephen Graham Jones'],
  ],
  'locus-sf': [
    [1980, 'Titan', 'John Varley'],
    [1981, 'The Snow Queen', 'Joan D. Vinge'],
    [1982, 'The Many-Colored Land', 'Julian May'],
    [1983, "Foundation's Edge", 'Isaac Asimov'],
    [1984, 'Startide Rising', 'David Brin'],
    [1985, 'The Integral Trees', 'Larry Niven'],
    [1986, 'The Postman', 'David Brin'],
    [1987, 'Speaker for the Dead', 'Orson Scott Card'],
    [1988, 'The Uplift War', 'David Brin'],
    [1989, 'Cyteen', 'C. J. Cherryh'],
    [1990, 'Hyperion', 'Dan Simmons'],
    [1991, 'The Fall of Hyperion', 'Dan Simmons'],
    [1992, 'Barrayar', 'Lois McMaster Bujold'],
    [1993, 'Doomsday Book', 'Connie Willis'],
    [1994, 'Green Mars', 'Kim Stanley Robinson'],
    [1995, 'Mirror Dance', 'Lois McMaster Bujold'],
    [1996, 'The Diamond Age', 'Neal Stephenson'],
    [1997, 'Blue Mars', 'Kim Stanley Robinson'],
    [1998, 'The Rise of Endymion', 'Dan Simmons'],
    [1999, 'To Say Nothing of the Dog', 'Connie Willis'],
    [2000, 'Cryptonomicon', 'Neal Stephenson'],
    [2001, 'The Telling', 'Ursula K. Le Guin'],
    [2002, 'Passage', 'Connie Willis'],
    [2003, 'The Years of Rice and Salt', 'Kim Stanley Robinson'],
    [2004, 'Ilium', 'Dan Simmons'],
    [2005, 'The Baroque Cycle', 'Neal Stephenson'],
    [2006, 'Accelerando', 'Charles Stross'],
    [2007, 'Rainbows End', 'Vernor Vinge'],
    [2008, "The Yiddish Policemen's Union", 'Michael Chabon'],
    [2009, 'Anathem', 'Neal Stephenson'],
    [2010, 'Boneshaker', 'Cherie Priest'],
    [2011, 'Blackout/All Clear', 'Connie Willis'],
    [2012, 'Embassytown', 'China Miéville'],
    [2013, 'Redshirts', 'John Scalzi'],
    [2014, "Abaddon's Gate", 'James S. A. Corey'],
    [2015, 'Ancillary Sword', 'Ann Leckie'],
    [2016, 'Ancillary Mercy', 'Ann Leckie'],
    [2017, "Death's End", 'Cixin Liu'],
    [2018, 'The Collapsing Empire', 'John Scalzi'],
    [2019, 'The Calculating Stars', 'Mary Robinette Kowal'],
    [2020, 'The City in the Middle of the Night', 'Charlie Jane Anders'],
    [2021, 'Network Effect', 'Martha Wells'],
    [2022, 'A Desolation Called Peace', 'Arkady Martine'],
    [2023, 'The Kaiju Preservation Society', 'John Scalzi'],
    [2024, 'System Collapse', 'Martha Wells'],
    [2025, 'The Man Who Saw Seconds', 'Alexander Boldizar'],
    [2026, 'Death of the Author', 'Nnedi Okorafor'],
  ],
  'locus-fantasy': [
    [1980, 'Harpist in the Wind', 'Patricia A. McKillip'],
    [1981, "Lord Valentine's Castle", 'Robert Silverberg'],
    [1982, 'The Claw of the Conciliator', 'Gene Wolfe'],
    [1983, 'The Sword of the Lictor', 'Gene Wolfe'],
    [1984, 'The Mists of Avalon', 'Marion Zimmer Bradley'],
    [1985, 'Job: A Comedy of Justice', 'Robert A. Heinlein'],
    [1986, 'Trumps of Doom', 'Roger Zelazny'],
    [1987, 'Soldier of the Mist', 'Gene Wolfe'],
    [1988, 'Seventh Son', 'Orson Scott Card'],
    [1989, 'Red Prophet', 'Orson Scott Card'],
    [1990, 'Prentice Alvin', 'Orson Scott Card'],
    [1991, 'Tehanu', 'Ursula K. Le Guin'],
    [1992, 'Beauty', 'Sheri S. Tepper'],
    [1993, 'Last Call', 'Tim Powers'],
    [1994, "The Innkeeper's Song", 'Peter S. Beagle'],
    [1995, 'Brittle Innings', 'Michael Bishop'],
    [1996, 'Alvin Journeyman', 'Orson Scott Card'],
    [1997, 'A Game of Thrones', 'George R. R. Martin'],
    [1998, 'Earthquake Weather', 'Tim Powers'],
    [1999, 'A Clash of Kings', 'George R. R. Martin'],
    [2000, 'Harry Potter and the Prisoner of Azkaban', 'J. K. Rowling'],
    [2001, 'A Storm of Swords', 'George R. R. Martin'],
    [2002, 'American Gods', 'Neil Gaiman'],
    [2003, 'The Scar', 'China Miéville'],
    [2004, 'Paladin of Souls', 'Lois McMaster Bujold'],
    [2005, 'Iron Council', 'China Miéville'],
    [2006, 'Anansi Boys', 'Neil Gaiman'],
    [2007, 'The Privilege of the Sword', 'Ellen Kushner'],
    [2008, 'Making Money', 'Terry Pratchett'],
    [2009, 'Lavinia', 'Ursula K. Le Guin'],
    [2010, 'The City & the City', 'China Miéville'],
    [2011, 'Kraken', 'China Miéville'],
    [2012, 'A Dance with Dragons', 'George R. R. Martin'],
    [2013, 'The Apocalypse Codex', 'Charles Stross'],
    [2014, 'The Ocean at the End of the Lane', 'Neil Gaiman'],
    [2015, 'The Goblin Emperor', 'Katherine Addison'],
    [2016, 'Uprooted', 'Naomi Novik'],
    [2017, 'All the Birds in the Sky', 'Charlie Jane Anders'],
    [2018, 'The Stone Sky', 'N. K. Jemisin'],
    [2019, 'Spinning Silver', 'Naomi Novik'],
    [2020, 'Middlegame', 'Seanan McGuire'],
    [2021, 'The City We Became', 'N. K. Jemisin'],
    [2022, 'Jade Legacy', 'Fonda Lee'],
    [2023, 'Babel', 'R. F. Kuang'],
    [2024, 'Witch King', 'Martha Wells'],
    [2025, 'A Sorceress Comes to Call', 'T. Kingfisher'],
    [2026, 'The Everlasting', 'Alix E. Harrow'],
  ],
  clarke: [
    [1987, "The Handmaid's Tale", 'Margaret Atwood'],
    [1988, 'The Sea and Summer', 'George Turner'],
    [1989, 'Unquenchable Fire', 'Rachel Pollack'],
    [1990, 'The Child Garden', 'Geoff Ryman'],
    [1991, 'Take Back Plenty', 'Colin Greenland'],
    [1992, 'Synners', 'Pat Cadigan'],
    [1993, 'Body of Glass', 'Marge Piercy'],
    [1994, 'Vurt', 'Jeff Noon'],
    [1995, 'Fools', 'Pat Cadigan'],
    [1996, 'Fairyland', 'Paul J. McAuley'],
    [1997, 'The Calcutta Chromosome', 'Amitav Ghosh'],
    [1998, 'The Sparrow', 'Mary Doria Russell'],
    [1999, 'Dreaming in Smoke', 'Tricia Sullivan'],
    [2000, 'Distraction', 'Bruce Sterling'],
    [2001, 'Perdido Street Station', 'China Miéville'],
    [2002, 'Bold as Love', 'Gwyneth Jones'],
    [2003, 'The Separation', 'Christopher Priest'],
    [2004, 'Quicksilver', 'Neal Stephenson'],
    [2005, 'Iron Council', 'China Miéville'],
    [2006, 'Air', 'Geoff Ryman'],
    [2007, 'Nova Swing', 'M. John Harrison'],
    [2008, 'Black Man', 'Richard Morgan'],
    [2009, 'Song of Time', 'Ian R. MacLeod'],
    [2010, 'The City & the City', 'China Miéville'],
    [2011, 'Zoo City', 'Lauren Beukes'],
    [2012, 'The Testament of Jessie Lamb', 'Jane Rogers'],
    [2013, 'Dark Eden', 'Chris Beckett'],
    [2014, 'Ancillary Justice', 'Ann Leckie'],
    [2015, 'Station Eleven', 'Emily St. John Mandel'],
    [2016, 'Children of Time', 'Adrian Tchaikovsky'],
    [2017, 'The Underground Railroad', 'Colson Whitehead'],
    [2018, 'Dreams Before the Start of Time', 'Anne Charnock'],
    [2019, 'Rosewater', 'Tade Thompson'],
    [2020, 'The Old Drift', 'Namwali Serpell'],
    [2021, 'The Animals in That Country', 'Laura Jean McKay'],
    [2022, 'Deep Wheel Orcadia', 'Harry Josephine Giles'],
    [2023, 'Venomous Lumpsucker', 'Ned Beauman'],
    [2024, 'In Ascension', 'Martin MacInnes'],
    [2025, 'Annie Bot', 'Sierra Greer'],
  ],
  'world-fantasy': [
    [1975, 'The Forgotten Beasts of Eld', 'Patricia A. McKillip'],
    [1976, 'Bid Time Return', 'Richard Matheson'],
    [1977, 'Doctor Rat', 'William Kotzwinkle'],
    [1978, 'Our Lady of Darkness', 'Fritz Leiber'],
    [1979, 'Gloriana', 'Michael Moorcock'],
    [1980, 'Watchtower', 'Elizabeth A. Lynn'],
    [1981, 'The Shadow of the Torturer', 'Gene Wolfe'],
    [1982, 'Little, Big', 'John Crowley'],
    [1983, 'Nifft the Lean', 'Michael Shea'],
    [1984, 'The Dragon Waiting', 'John M. Ford'],
    [1985, 'Bridge of Birds', 'Barry Hughart'],
    [1985, 'Mythago Wood', 'Robert Holdstock'],
    [1986, 'Song of Kali', 'Dan Simmons'],
    [1987, 'Perfume', 'Patrick Süskind'],
    [1988, 'Replay', 'Ken Grimwood'],
    [1989, 'Koko', 'Peter Straub'],
    [1990, 'Lyonesse: Madouc', 'Jack Vance'],
    [1991, 'Only Begotten Daughter', 'James Morrow'],
    [1991, 'Thomas the Rhymer', 'Ellen Kushner'],
    [1992, "Boy's Life", 'Robert R. McCammon'],
    [1993, 'Last Call', 'Tim Powers'],
    [1994, 'Glimpses', 'Lewis Shiner'],
    [1995, 'Towing Jehovah', 'James Morrow'],
    [1996, 'The Prestige', 'Christopher Priest'],
    [1997, 'Godmother Night', 'Rachel Pollack'],
    [1998, 'The Physiognomy', 'Jeffrey Ford'],
    [1999, 'The Antelope Wife', 'Louise Erdrich'],
    [2000, 'Thraxas', 'Martin Scott'],
    [2001, 'Declare', 'Tim Powers'],
    [2001, 'Galveston', 'Sean Stewart'],
    [2002, 'The Other Wind', 'Ursula K. Le Guin'],
    [2003, 'Ombria in Shadow', 'Patricia A. McKillip'],
    [2003, 'The Facts of Life', 'Graham Joyce'],
    [2004, 'Tooth and Claw', 'Jo Walton'],
    [2005, 'Jonathan Strange & Mr Norrell', 'Susanna Clarke'],
    [2006, 'Kafka on the Shore', 'Haruki Murakami'],
    [2007, 'Soldier of Sidon', 'Gene Wolfe'],
    [2008, 'Ysabel', 'Guy Gavriel Kay'],
    [2009, 'The Shadow Year', 'Jeffrey Ford'],
    [2009, 'Tender Morsels', 'Margo Lanagan'],
    [2010, 'The City & the City', 'China Miéville'],
    [2011, 'Who Fears Death', 'Nnedi Okorafor'],
    [2012, 'Osama', 'Lavie Tidhar'],
    [2013, 'Alif the Unseen', 'G. Willow Wilson'],
    [2014, 'A Stranger in Olondria', 'Sofia Samatar'],
    [2015, 'The Bone Clocks', 'David Mitchell'],
    [2016, 'The Chimes', 'Anna Smaill'],
    [2017, 'The Sudden Appearance of Hope', 'Claire North'],
    [2018, 'The Changeling', 'Victor LaValle'],
    [2018, 'Jade City', 'Fonda Lee'],
    [2019, 'Witchmark', 'C. L. Polk'],
    [2020, 'Queen of the Conquered', 'Kacen Callender'],
    [2021, 'Trouble the Saints', 'Alaya Dawn Johnson'],
    [2022, 'The Jasmine Throne', 'Tasha Suri'],
    [2023, "Saint Death's Daughter", 'C. S. E. Cooney'],
    [2024, 'The Reformatory', 'Tananarive Due'],
    [2025, 'The Tainted Cup', 'Robert Jackson Bennett'],
  ],
}
